# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ad00b3425497056defe9d44f81e940e42c33f7c45b701e4f2cac87f73143302fb67f9900b118503a16f3e27881d6ec08f5137cf4c9cf34a58329308e08d476

test:
  secret_key_base: 518cbae81f397e3cb138cf3db3337b1863da5b18f99f7f292c98bcb0c707e8157be5bb15a1d0ef57f29c73c9587111cf74bfd0be1d247268b2a2568fd7e475e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
